# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: mealplannr/circleci-react-webapp:1.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Build the app
          command: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - build

  dev-deploy:
    docker:
      - image: mealplannr/circleci-react-webapp:1.0

    working_directory: ~/repo

    steps:

      - attach_workspace:
          at: ~/repo

      - run:
          name: Copy files to S3
          command: aws s3 sync build/ s3://meal-planner-frontend-app-dev --delete

      - run:
          name: Invalidate Cloudfront cache
          command: aws cloudfront create-invalidation --distribution-id EYW4YI3QNQJ5U --paths "/*"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - dev-deploy:
          requires:
            - build
